# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3f9a1e5c6dc514513536624dbd710e4788914e8680be083a6e6522a8a2c6e9171286ef61092c44978b3550a2b540d545da074e99b894bdb8b2fa8ddeaaae379

test:
  secret_key_base: d9fc0db3eae4cc64b1c8ed75f3bac9a576483fc177d2719f6d0d98680bba0ade7465e41e2b8dae8521e9594d170898911747733660203bc58ef554f598493d57

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
